### ISSUE TITLE
Determine proper way to reference API access keys

### ISSUE THREAD

**Issue by jzhang005** [webdev-nyc-air-quality/webdev-nyc-air-quality#26]
Like Google Map API key is private information if someone uses it outside our project may produce cost on our members' google account, so we need to look into how to make it private in our repo but can be used in Gatsby develop and AWS built.

**Comment by ian-s-mcb** [comment]
Fixed in #46 

Followed guides:
https://www.gatsbyjs.org/docs/environment-variables/
https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html
