### ISSUE TITLE
Look into AWS amplify work as a team

### ISSUE THREAD

**Issue by jzhang005** [webdev-nyc-air-quality/webdev-nyc-air-quality#31]
We need to have a project that everyone in our team can see and edit on AWS amplify. We need to look into how to make that possible, otherwise, we will still have individual work and will be hard to merge them at the end.

**Comment by ian-s-mcb** [comment]
The Design Compass team wrote a guide for us on team workflow for AWS Amplify and it worked well.

https://github.com/rdiaz002/Sharing-your-Amplify-project-
