### ISSUE TITLE
Geocoding form

### ISSUE THREAD

**Issue by TadjM** [webdev-nyc-air-quality/webdev-nyc-air-quality#58]
* Used a  react-geocoding library
* Add a form to check validity of address
* Return the latitude and longitude of the address 
* [ Link to the geocode library]( https://github.com/shukerullah/react-geocode)
* Or we can instead make a  call directly to the google api
* [Link to react api and ajax](https://reactjs.org/docs/faq-ajax.html)
* [google geocode api](https://developers.google.com/maps/documentation/geocoding/start?utm_source=google&utm_medium=cpc&utm_campaign=FY18-Q2-global-demandgen-paidsearchonnetworkhouseads-cs-maps_contactsal_saf&utm_content=text-ad-none-none-DEV_c-CRE_315916117598-ADGP_Hybrid+%7C+AW+SEM+%7C+BKWS+~+Google+Maps+Geocoding+API-KWID_43700040099688311-aud-581578347266:kwd-332054270084-userloc_9004174&utm_term=KW_google%20geocode%20api-ST_google+geocode+api&gclid=CL3l2MWtkuICFYn0swod0v4FJg)

**Comment by ian-s-mcb** [comment]
@TadjM fixed in #62
